customer/urls.py
from django.urls import path
from. import views

app_name = "customer"

urlpatterns = [   
   path('',views.customer_home, name='customer_home'),
   path('store',views.store,name='store'),
   path('product/detail',views.product_detail,name='product_detail'),
   path('cart',views.cart,name='cart'),
   path('placeOrder',views.place_order,name='place_order'),
   path('order/successc',views.order_complete,name='order_complete'),
   path('dashboard',views.dashboard,name='dasboard'),
   path('seller/register',views.seller_register,name='seller_register'),
   path('seller/login',views.seller_login,name='seller_login'),
   path('customer/signup',views.customer_signup,name='customer_signup'),
   path('customer/login',views.customer_login,name='customer_login'),
   path('forgotPassword/customer',views.forgot_password_customer,name='forgot_password_customer'),
   path('forgotPassword/seller',views.forgot_password_seller,name='forgot_password_seller'),
   

]

eKart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ekart/', include('eKart_admin.urls')),
    path('seller/', include('seller.urls')),
    path('', include('customer.urls'))

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/models.py
from datetime import date
from django.db import models

# Create your models here.

class Customer(models.Model):
    first_name = models.CharField(max_length =  20)
    last_name =  models.CharField(max_length =  20)
    email =  models.CharField(max_length =  50)
    mobile = models.BigIntegerField(default = 0)
    gender = models.CharField(max_length = 10)
    city = models.CharField(max_length = 20)
    country = models.CharField(max_length = 20)
    password = models.CharField(max_length = 20)
    is_password_changed = models.BooleanField(default = False)
    last_changed_on = models.DateField(default = date.today)

    class Meta:
        db_table = 'customer_tb'

customer/views.py
from django.shortcuts import redirect, render
from customer.models import Customer
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from seller.models import Product, Seller
# from .models import Customer
# Create your views here.


def customer_home(request):
    products=Product.objects.all()
    context={
        'products':products,

    }
    return render(request, 'customer/customer_home.html', context)


def store(request):
    query = request.GET.get('query', 'all')
    
    if query == 'all':
        products = Product.objects.all()
     
    else:
         
        products = Product.objects.filter(category = query)

    if  'search_text' in request.GET:
        search_text = request.GET.get('search_text')
        products = Product.objects.filter(Q(category__category__icontains = search_text) | Q(product_name__icontains = search_text))
    # Pagination
    paginator = Paginator(products, 1)  # Number of products per page
    page_number = request.GET.get('page')
    try:
        paginated_products = paginator.page(page_number)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        paginated_products = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        paginated_products = paginator.page(paginator.num_pages)
    context = {
        'products': paginated_products,
        'product_count': paginator.count
    }

    return render(request, 'customer/store.html', context)


def product_detail(request):
    return render(request, 'customer/product_detail.html')


def cart(request):
    return render(request, 'customer/cart.html')


def place_order(request):
    return render(request, 'customer/place_order.html')


def order_complete(request):
    return render(request, 'customer/order_complete.html')


def dashboard(request):
    return render(request, 'customer/dashboard.html')


def seller_register(request):
    message = ''
    if request.method == 'POST':  
        first_name = request.POST['fname'] 
        last_name = request.POST['lastname']
        email = request.POST['email']
        gender = request.POST['gender']
        company_name = request.POST['cmp_name']
        city = request.POST['city']
        country = request.POST['country']
        account_no = request.POST['acc_no']
        bank_name = request.POST['bank_name']
        branch = request.POST['branch']
        ifsc = request.POST['ifsc']
        pic = request.FILES['pic']
       
        seller_exist = Seller.objects.filter(email = email).exists()

        if not seller_exist: 

            seller = Seller(first_name = first_name, last_name = last_name, company_name = company_name,    gender = gender, email = email, 
                            city = city, country = country, account_no = account_no, bank_name = bank_name,
                            branch_name = branch, ifsc = ifsc, pic = pic)
            seller.save()
            message = 'Registration Succesful'
        else:
            message = 'Email Exists'
    return render(request, 'customer/seller_register.html', {'message': message})



def seller_login(request):
    message = ''
    if request.method == 'POST':
        username = request.POST['seller_id']
        password = request.POST['password']

        seller = Seller.objects.filter(login_id = username, password = password)

        if seller.exists():
            request.session['seller'] = seller[0].id
            request.session['seller_name'] = seller[0].first_name + ' ' + seller[0].last_name
            return redirect('Seller:seller_home')

        else:

            message = 'Invalid Username Or Password'
    context={
        'message':message,
    } #dictionary, used if theres a lot
    return render(request, 'customer/seller_login.html', context)


def customer_signup(request):
    message = ''
    status = False
    if request.method == 'POST':  
        first_name = request.POST['fname'] 
        last_name = request.POST['lastname']
        email = request.POST['email']
        gender = request.POST['gender']
        city = request.POST['city']
        country = request.POST['country']
        password = request.POST['password']

        
        
        customer_exist = Customer.objects.filter(email = email).exists()

        if not customer_exist: 

            customer = Customer(first_name = first_name, last_name = last_name, gender = gender, email = email, 
                            city = city, country = country, password = password)
            customer.save()
            message = 'Registration Succesful'
            status = True



    return render(request, 'customer/customer_signup.html', {'message': message, 'status': status})



def customer_login(request):

    message = ''
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        
        try:
            customer = Customer.objects.get(email = email, password = password)
            request.session['customer'] = customer.id
            request.session['customer_name'] = customer.first_name + ' ' + customer.last_name
            return redirect('customer:customer_home')

        except:
            message = 'Invalid Username Or Password'

    return render(request, 'customer/customer_login.html', {'message':message})


def forgot_password_customer(request):
    return render(request, 'customer/forgot_password_customer.html')


def forgot_password_seller(request):
    return render(request, 'customer/forgot_password_seller.html')

customer/templates/customer/base.html
{% load static%}
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="max-age=604800" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>GreatKart | One of the Biggest Online Shopping Platform</title>

<link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">

<!-- jQuery -->
<script src="{% static 'js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>

<!-- Bootstrap4 files-->
<script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href="{% static 'fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">

<!-- custom style -->
<link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)" />

<!-- custom javascript -->
<script src="{% static 'js/script.js' %}" type="text/javascript"></script>

<script type="text/javascript">
/// some script

// jquery ready start
$(document).ready(function() {
	// jQuery code

}); 
// jquery end
</script>

</head>
<body>
   <!-- navbar -->
   {% include 'customer/includes/navbar.html' %}
    {% block content%}

    {% endblock %}

    <!-- footer -->
    {% include 'customer/includes/footer.html' %}
</body>
</html>

customer/templates/customer/cart.html
{% extends 'customer/base.html' %}
{% load static %}

{% block content %}
<section class="section-content padding-y bg">
    <div class="container">

        <!-- ============================ COMPONENT 1 ================================= -->

        <div class="row">
            <aside class="col-lg-9">
                <div class="card">
                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Product</th>
                                <th scope="col" width="120">Quantity</th>
                                <th scope="col" width="120">Price</th>
                                <th scope="col" class="text-right" width="200"> </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <figure class="itemside align-items-center">
                                        <div class="aside"><img src="{% static './images/items/11.jpg' %}" class="img-sm"></div>
                                        <figcaption class="info">
                                            <a href="#" class="title text-dark">Camera Canon EOS M50 Kit</a>
                                            <p class="text-muted small">Matrix: 25 Mpx <br> Brand: Canon</p>
                                        </figcaption>
                                    </figure>
                                </td>
                                <td>
                                    <!-- col.// -->
                                    <div class="col">
                                        <div class="input-group input-spinner">
                                            <div class="input-group-prepend">
                                                <button class="btn btn-light" type="button" id="button-plus"> <i
                                                        class="fa fa-minus"></i> </button>
                                            </div>
                                            <input type="text" class="form-control" value="1">
                                            <div class="input-group-append">
                                                <button class="btn btn-light" type="button" id="button-minus"> <i
                                                        class="fa fa-plus"></i> </button>
                                            </div>
                                        </div> <!-- input-group.// -->
                                    </div> <!-- col.// -->
                                </td>
                                <td>
                                    <div class="price-wrap">
                                        <var class="price">$1156.00</var>
                                        <small class="text-muted"> $315.20 each </small>
                                    </div> <!-- price-wrap .// -->
                                </td>
                                <td class="text-right">
                                    <a href="" class="btn btn-danger"> Remove</a>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <figure class="itemside align-items-center">
                                        <div class="aside"><img src="{% static './images/items/10.jpg' %}" class="img-sm"></div>
                                        <figcaption class="info">
                                            <a href="#" class="title text-dark">ADATA Premier ONE microSDXC</a>
                                            <p class="text-muted small">Size: 256 GB <br> Brand: ADATA </p>
                                        </figcaption>
                                    </figure>
                                </td>
                                <td>
                                    <!-- col.// -->
                                    <div class="col">
                                        <div class="input-group input-spinner">
                                            <div class="input-group-prepend">
                                                <button class="btn btn-light" type="button" id="button-plus"> <i
                                                        class="fa fa-minus"></i> </button>
                                            </div>
                                            <input type="text" class="form-control" value="1">
                                            <div class="input-group-append">
                                                <button class="btn btn-light" type="button" id="button-minus"> <i
                                                        class="fa fa-plus"></i> </button>
                                            </div>
                                        </div> <!-- input-group.// -->
                                    </div> <!-- col.// -->
                                </td>
                                <td>
                                    <div class="price-wrap">
                                        <var class="price">$149.97</var>
                                        <small class="text-muted"> $75.00 each </small>
                                    </div> <!-- price-wrap .// -->
                                </td>
                                <td class="text-right">
                                    <a href="" class="btn btn-danger"> Remove</a>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <figure class="itemside align-items-center">
                                        <div class="aside"><img src="{% static './images/items/9.jpg' %}" class="img-sm"></div>
                                        <figcaption class="info">
                                            <a href="#" class="title text-dark">Logitec headset for gaming</a>
                                            <p class="small text-muted">Version: CUH-ZCT2E <br> Brand: Sony</p>
                                        </figcaption>
                                    </figure>
                                </td>
                                <td>
                                    <!-- col.// -->
                                    <div class="col">
                                        <div class="input-group input-spinner">
                                            <div class="input-group-prepend">
                                                <button class="btn btn-light" type="button" id="button-plus"> <i
                                                        class="fa fa-minus"></i> </button>
                                            </div>
                                            <input type="text" class="form-control" value="1">
                                            <div class="input-group-append">
                                                <button class="btn btn-light" type="button" id="button-minus"> <i
                                                        class="fa fa-plus"></i> </button>
                                            </div>
                                        </div> <!-- input-group.// -->
                                    </div> <!-- col.// -->
                                </td>
                                <td>
                                    <div class="price-wrap">
                                        <var class="price">$98.00</var>
                                        <small class="text-muted"> $578.00 each</small>
                                    </div> <!-- price-wrap .// -->
                                </td>
                                <td class="text-right">
                                    <a href="" class="btn btn-danger"> Remove</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div> <!-- card.// -->

            </aside> <!-- col.// -->
            <aside class="col-lg-3">

                <div class="card">
                    <div class="card-body">
                        <dl class="dlist-align">
                            <dt>Total price:</dt>
                            <dd class="text-right">$69.97</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Tax:</dt>
                            <dd class="text-right"> $10.00</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Total:</dt>
                            <dd class="text-right text-dark b"><strong>$59.97</strong></dd>
                        </dl>
                        <hr>
                        <p class="text-center mb-3">
                            <img src="{% static './images/misc/payments.png' %}" height="26">
                        </p>
                        <a href="{% url 'customer:order_complete' %}" class="btn btn-primary btn-block"> Checkout </a>
                        <a href="{% url 'customer:store' %}" class="btn btn-light btn-block">Continue Shopping</a>
                    </div> <!-- card-body.// -->
                </div> <!-- card.// -->

            </aside> <!-- col.// -->


        </div> <!-- row.// -->
        <!-- ============================ COMPONENT 1 END .// ================================= -->

    </div> <!-- container .//  -->
</section>
<!-- ==============

{% endblock %}

customer/templates/customer/customer_home.html
{% extends 'customer/base.html' %}
{% load static %}

{% block content %}


<!-- ========================= SECTION MAIN ========================= -->
<section class="section-intro padding-y-sm">
    <div class="container">
    
    <div class="intro-banner-wrap">
        <img src="{% static 'images/banners/1.jpg' %}" class="img-fluid rounded">
    </div>
    
    </div> <!-- container //  -->
    </section>
    <!-- ========================= SECTION MAIN END// ========================= -->
    
    <!-- ========================= SECTION  ========================= -->
    <section class="section-name padding-y-sm">
    <div class="container">
    
    <header class="section-heading">
        <a href="{% url 'customer:store' %}" class="btn btn-outline-primary float-right">See all</a>
        <h3 class="section-title">Popular products</h3>
    </header><!-- sect-heading -->
    
        
    <div class="row">
        {% for product in products %}
        <div class="col-md-3">
            <div class="card card-product-grid">
                <a href="{% url 'customer:product_detail' %}" class="img-wrap"> <img src="{{product.image.url}}"> </a>
                <figcaption class="info-wrap">
                    <a href="{% url 'customer:product_detail' %}" class="title">{{product.product_name}}</a>
                    <div class="price mt-1">RS{{product.price}}</div> <!-- price-wrap.// -->
                </figcaption>
            </div>
        </div> <!-- col.// -->
        {% endfor %}
    </div> <!-- row.// -->
    
    </div><!-- container // -->
    </section>
    <!-- ========================= SECTION  END// ========================= -->
    
    

{% endblock %}

customer/templates/customer/customer_login.html
{% extends 'customer/base.html' %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->
        <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
          <div class="card-body">
          <h4 class="card-title mb-4"> Customer Sign in</h4>
          <form method="post">
            {% csrf_token %}
              <div class="form-group">
                 <input type="email" class="form-control" placeholder="Email Address" name="email">
              </div> <!-- form-group// -->
              <div class="form-group">
                <input type="password" class="form-control" placeholder="Password" name="password">
              </div> <!-- form-group// -->
              
              <div class="form-group">
                  <a href="{% url 'customer:forgot_password_customer'%}" class="float-right">Forgot password?</a> 
               
              </div> <!-- form-group form-check .// -->
              <div class="form-group">
                  <!-- <button type="submit" class="btn btn-primary btn-block"> Login  </button> -->
                  <button class="btn btn-primary btn-block"> Login  </button>
              </div> <!-- form-group// -->    
          </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
      {{message}}
      
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

customer/templates/customer/forgot_password_customer.html
{% extends 'customer/base.html' %}
{% load static %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->
        <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
          <div class="card-body">
          <h4 class="card-title mb-4"> Enter your Email id </h4>
          <form>
              <div class="form-group">
                 <input type="email" class="form-control" placeholder="Email Address" >
              </div> <!-- form-group// -->
              
    
              <div class="form-group">
                  <!-- <button type="submit" class="btn btn-primary btn-block"> Login  </button> -->
                  <a href="" class="btn btn-primary btn-block"> Submit  </a>
              </div> <!-- form-group// -->    
          </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
        
      
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

customer/templates/customer/seller_login.html
{% extends 'customer/base.html' %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->
        <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
          <div class="card-body">
          <h4 class="card-title mb-4">Seller Sign in</h4>
          <form method="post">
            {% csrf_token %}
              <div class="form-group">
                 <input type="text" class="form-control" placeholder="Seller Id" name="seller_id">
              </div> <!-- form-group// -->
              <div class="form-group">
                <input type="password" class="form-control" placeholder="Password" name="password">
              </div> <!-- form-group// -->
              
              <div class="form-group">
                  <a href="{% url 'customer:forgot_password_seller' %}" class="float-right">Forgot password?</a> 
               
              </div> <!-- form-group form-check .// -->
              <div class="form-group">
                  <!-- <button type="submit" class="btn btn-primary btn-block"> Login  </button> -->
                  <button class="btn btn-primary btn-block">Login</button>
              </div> <!-- form-group// -->    
          </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
         <p class="text-center mt-4">Don't have account? <a href="{% url 'customer:seller_register' %}">Sign up</a></p>
         <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    
    

{% endblock%}

customer/templates/customer/store.html
{% extends 'customer/base.html' %}
{% load static %}

{% block content %}

<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
    <div class="container">
        <h2 class="title-page">Our Store</h2>

    </div> <!-- container //  -->
</section>
<!-- ========================= SECTION INTRO END// ========================= -->

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
    <div class="container">

        <div class="row">
            <aside class="col-md-3">

                <div class="card">
                    <article class="filter-group">
                        <header class="card-header">
                            <a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
                                <i class="icon-control fa fa-chevron-down"></i>
                                <h6 class="title">Categories</h6>
                            </a>
                        </header>
                        <div class="filter-content collapse show" id="collapse_1">
                            <div class="card-body">

                                <ul class="list-menu">
                                    {% for item in category_list %}
                                <li><a class="dropdown-item" href="{% url 'customer:store' %}?query={{ item.id }}">{{item.category }} </a></li>
                                {% endfor %}
                                </ul>

                            </div> <!-- card-body.// -->
                        </div>
                    </article> <!-- filter-group  .// -->

                </div> <!-- card.// -->

            </aside> <!-- col.// -->
            <main class="col-md-9">

                <header class="border-bottom mb-4 pb-3">
                    <div class="form-inline">
                        <span class="mr-md-auto">{{product_count}} Items found </span>

                    </div>
                </header><!-- sect-heading -->

                <div class="row">
                    {% for product in products %}
                    <div class="col-md-4">
                        <figure class="card card-product-grid">
                            <div class="img-wrap">
                                <a href="{% url 'customer:product_detail' %}">
                                    <img src="{{product.image.url}}">
                                </a>
                            </div> <!-- img-wrap.// -->
                            <figcaption class="info-wrap">
                                <div class="fix-height">
                                    <a href="{% url 'customer:product_detail' %}" class="title">{{product.product_name}}</a>
                                    <div class="price-wrap mt-2">
                                        <span class="price">RS{{product.price}}</span>
                                        <del class="price-old">RS</del>
                                    </div> <!-- price-wrap.// -->
                                </div>
                                
                            </figcaption>
                        </figure>
                    </div> <!-- col.// -->
                    {% endfor %}
                </div> <!-- row end.// -->


                <nav class="mt-4" aria-label="Page navigation">
                    <ul class="pagination">
                        <!-- Previous page link -->
                        {% if products.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <span class="page-link">Previous</span>
                            </li>
                        {% endif %}
            
                        <!-- Page links -->
                        {% for page_num in products.paginator.page_range %}
                            <li class="page-item {% if page_num == products.number %}active{% endif %}">
                                <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                            </li>
                        {% endfor %}
            
                        <!-- Next page link -->
                        {% if products.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ products.next_page_number }}">Next</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <span class="page-link">Next</span>
                            </li>
                        {% endif %}
                    </ul>
                </nav>

            </main> <!-- col.// -->

        </div>

    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->



{% endblock %}