eKart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ekart/', include('eKart_admin.urls')),
    path('seller/', include('seller.urls')),
    path('', include('customer.urls'))

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from. import views

app_name = "Seller"

urlpatterns = [   
    path('',views.seller_home,name="seller_home"),
    path('product/add',views.add_product,name="add_product"),
    # path('add_category',views.add_category,name="add_category"),
    path('product',views.view_products,name="view_product"),
    # path('view_category',views.view_category,name="view_category"),
    path('profile',views.profile,name="profile"),
    path('myOrders',views.view_orders,name="view_orders"),
    path('stock/update',views.update_stock,name="update_stock"),
    path('order/history',views.order_history,name="order_history"),

   
]

seller/models.py
from django.db import models

from eKart_admin.models import Category

# Create your models here.

class Seller(models.Model):
    first_name = models.CharField(max_length =  20)
    last_name =  models.CharField(max_length =  20)
    company_name = models.CharField(max_length = 20)
    email =  models.CharField(max_length =  50)
    gender = models.CharField(max_length = 10)
    city = models.CharField(max_length = 20)
    country = models.CharField(max_length = 20)
    password = models.CharField(max_length = 20)
    pic = models.ImageField(upload_to = 'seller/')
    login_id = models.IntegerField(null = True)
    password = models.CharField(max_length = 20)
    account_no = models.BigIntegerField()
    bank_name = models.CharField(max_length = 20)
    branch_name = models.CharField(max_length = 20)
    ifsc = models.CharField(max_length = 20)

    status = models.CharField(max_length = 20, default = 'pending')

    class Meta:
        db_table = 'seller_tb'

class Product(models.Model):
    product_no = models.CharField(max_length =  30)
    product_name =  models.CharField(max_length =  20)
    category = models.ForeignKey(Category, on_delete = models.CASCADE)
    seller = models.ForeignKey(Seller, on_delete = models.CASCADE)
    description =  models.CharField(max_length =  200)
    stock = models.IntegerField()
    price = models.FloatField()
    image = models.ImageField(upload_to = 'product/')
    rating = models.FloatField(default = 0)
    status = models.CharField(max_length = 20, default = 'available')
    
    class Meta:
        db_table = 'product_tb'

seller/views.py
from django.shortcuts import render
from eKart_admin.models import Category

from seller.models import Product, Seller


# Create your views here.
def seller_home(request):
    return render(request, 'seller/seller_home.html')

def add_product(request):
    category_list = Category.objects.all()
    message = ''

    if request.method == 'POST':
        product_no = request.POST['product_code']
        product_name = request.POST['product_name']
        category = request.POST['category']
        description = request.POST['description']
        stock = request.POST['stock']
        price = request.POST['price']
        image = request.FILES['image']
        seller = request.session['seller']
        

       
             
        product, created = Product.objects.get_or_create(product_no = product_no, seller = seller, defaults = {
            'product_no': product_no, 
            'product_name': product_name.lower(),
            'seller': Seller.objects.get(id = seller),
            'category': Category.objects.get(id = category),
            'description': description.lower(),
            'stock': stock,
            'price': price,
            'image': image,
        })

        if created:
            print('added')
            message = 'Product Added'
        
        else:
            print('else')
            message = 'Product No Already exists'

       

    context = {
        'category': category_list,
        'message': message
    }
    return render(request, 'seller/add_product.html', context)

def add_category(request):
    return render(request, 'seller/add_category.html')

def view_category(request):
    return render(request, 'seller/view_category.html')

def view_products(request):
    products=Product.objects.filter(seller_id=request.session['seller'])
    return render(request, 'seller/view_product.html', {'products':products})

def profile(request):
    return render(request,'seller/profile.html')

def view_orders(request):
    return render(request,'seller/view_orders.html')

def update_stock(request):
    return render(request,'seller/update_stock.html')

def order_history(request):
    return render(request,'seller/order_history.html')

seller/templates/seller/includes/footer.html
<!-- ========================= FOOTER ========================= -->
<footer class="section-footer border-top">
	<div class="container">
		<section class="footer-bottom border-top row">
			<div class="col-md-2">
				<p class="text-muted"> &copy 2019 Company name </p>
			</div>
			<div class="col-md-8 text-md-center">
				<span  class="px-2">info@pixsellz.io</span>
				<span  class="px-2">+879-332-9375</span>
				<span  class="px-2">Street name 123, Avanue abc</span>
			</div>
			<div class="col-md-2 text-md-right text-muted">
				<i class="fab fa-lg fa-cc-visa"></i>
				<i class="fab fa-lg fa-cc-paypal"></i>
				<i class="fab fa-lg fa-cc-mastercard"></i>
			</div>
		</section>
	</div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->

seller/templates/seller/includes/navbar.html
{% load static %}

<header class="section-header">
    <nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTop4">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
                 <a href="#" class="nav-link">   English </a>
                
            </li>
            <li class="nav-item dropdown">
                <a href="#" class="nav-link"> USD </a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li><a href="#" class="nav-link"> <i class="fa fa-envelope"></i> Email </a></li>
            <li><a href="#" class="nav-link"> <i class="fa fa-phone"></i> Call us </a></li>
        </ul> <!-- list-inline //  -->
      </div> <!-- navbar-collapse .// -->
    </div> <!-- container //  -->
    </nav>
    
    <section class="header-main border-bottom">
        <div class="container">
    <div class="row align-items-center">
        <div class="col-lg-2 col-md-3 col-6">
            <a href="./" class="brand-wrap">
                <img class="logo" src="{% static './images/logo.png' %}">
            </a> <!-- brand-wrap.// -->
        </div>
        <div class="col-10">
            {% if request.session.seller  %}
            <p class="text-right">Welcome, {{request.session.seller_name}}</p>
            {% else  %}
            <p>Please Login</p>
            {% endif %}
        </div>            
    
            </div> <!-- row.// -->
        </div> <!-- container.// -->
    </section> <!-- header-main .// -->
    
    
    
    
    </header> <!-- section-header.// -->
    
    

seller/templates/seller/includes/sidebar.html
<aside class="col-md-3">
    <!--   SIDEBAR   -->
    <ul class="list-group">
        <a class="list-group-item active" href="{% url 'Seller:add_product' %}"> Add Products </a>
        <a class="list-group-item" href="{% url 'Seller:view_product' %}"> My Products </a>
        <a class="list-group-item" href="{% url 'Seller:update_stock' %}"> Update Stock </a>
        <a class="list-group-item" href="{% url 'Seller:profile' %}"> Profile </a>
        <a class="list-group-item" href="{% url 'Seller:view_orders' %}"> My orders </a>
        <a class="list-group-item" href="{% url 'Seller:order_history' %}"> Order history </a>
    </ul>
    <br>
    <a class="btn btn-light btn-block" href="#"> <i class="fa fa-power-off"></i> <span class="text">Log
            out</span> </a>
    <!--   SIDEBAR .//END   -->
</aside>