customer/urls.py
from django.urls import path
from. import views

app_name = "customer"

urlpatterns = [   
   path('',views.customer_home, name='customer_home'),
   path('store',views.store,name='store'),
   path('product/detail',views.product_detail,name='product_detail'),
   path('cart',views.cart,name='cart'),
   path('placeOrder',views.place_order,name='place_order'),
   path('order/successc',views.order_complete,name='order_complete'),
   path('dashboard',views.dashboard,name='dasboard'),
   path('seller/register',views.seller_register,name='seller_register'),
   path('seller/login',views.seller_login,name='seller_login'),
   path('customer/signup',views.customer_signup,name='customer_signup'),
   path('customer/login',views.customer_login,name='customer_login'),
   path('forgotPassword/customer',views.forgot_password_customer,name='forgot_password_customer'),
   path('forgotPassword/seller',views.forgot_password_seller,name='forgot_password_seller'),
   

]

eKart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ekart/', include('eKart_admin.urls')),
    path('seller/', include('seller.urls')),
    path('', include('customer.urls'))

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eKart_admin/urls.py
from django.urls import path
from. import views

app_name = "ekart_admin"

urlpatterns = [   
   path('',views.admin_home,name="admin_home"),
   path('category/add',views.add_category,name="add_category"),
   path('category/list',views.view_category,name="view_category"),
   path('sellers/list/pending',views.pending_sellers,name="pending_sellers"),
   path('sellers/list/approved',views.approved_sellers,name="approved_sellers"),
   path('customers/list',views.customers,name="customers"),
   path('admin_login/', views.admin_login, name="admin_login"),
   path('approve_seller/<int:id>', views.approve_seller, name="approve_seller"),
]

eKart_admin/models.py
from django.db import models

# Create your models here.

class EkartAdmin(models.Model):
    user_name = models.CharField(max_length = 20)
    password = models.CharField(max_length = 20)

    class Meta:
        db_table = 'admin_tb'

class Category(models.Model):
    category = models.CharField(max_length = 20)
    description = models.CharField(max_length = 200)
    cover_pic = models.ImageField(upload_to = 'category/')

    class Meta:
        db_table = 'category_tb'

eKart_admin/views.py
from random import randint
from django.shortcuts import redirect, render
from eKart import settings

from eKart_admin.models import Category, EkartAdmin
from seller.models import Seller
from django.core.mail import send_mail

# Create your views here.
def admin_home(request):
    return render(request,'ekart_admin/admin_home.html')

def view_category(request):
    categories=Category.objects.all()
    return render(request,'ekart_admin/view_category.html', {'categories':categories})

def add_category(request):
    message = ''
    

    if request.method == 'POST':
        category = request.POST['category_name'].lower()
        description = request.POST['description']
        cover_pic = request.FILES['category_image']

        category_exist = Category.objects.filter(category = category).exists()

        if not category_exist:
            category = Category(category = category, description = description, cover_pic = cover_pic)
            category.save()
            message = 'Category Added'
            
        else:
            message = 'Already Added'
    return render(request,'ekart_admin/add_category.html', {'message': message, })

def pending_sellers(request):
    pending_sellers=Seller.objects.filter(status='pending')
    return render(request,'ekart_admin/pending_sellers.html', {'pending_sellers':pending_sellers})

def approved_sellers(request):
    approved_sellers=Seller.objects.filter(status='active')
    print(approved_sellers)
    return render(request,'ekart_admin/approved_sellers.html', {'approved_sellers':approved_sellers})

def customers(request):
    return render(request,'ekart_admin/customers.html')

def admin_login(request):
    message = ''
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        try:
            admin = EkartAdmin.objects.get(user_name = username, password = password)
            return redirect('ekart_admin:admin_home')
        except Exception as e:
            print(e)
            message = 'Invalid Username Or Password'


    return render(request,'ekart_admin/admin_login.html', {'message': message,})
    
def approve_seller(request,id):

    seller = Seller.objects.get(id = id)
    seller_id = randint(11111, 999999)
    temporary_password = 'sel-' + str(seller_id)  
    subject = 'username and temporary password'
    message = 'Hi! your Ekart account has been approved, your seller id is ' + str(seller_id) + temporary_password + ' and temporary password is ' + str(temporary_password)
    from_email = settings.EMAIL_HOST_USER
    # recipient_list = [seller.email,]
    recipient_list = ['daniyaashah@gmail.com',]

    send_mail(
        subject = subject,
        message = message,
        from_email = from_email,
        recipient_list = recipient_list
    )

    Seller.objects.filter(id = id).update(login_id = seller_id, password = temporary_password, status = 'active')

    return redirect('ekart_admin:pending_sellers')

eKart_admin/templates/ekart_admin/includes/navbar.html
{% load static %}

<header class="section-header">

    <section class="header-main border-bottom">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-2 col-md-3 col-6">
                    <a href="{% url 'ekart_admin:admin_home' %}" class="brand-wrap">
                        <img class="logo" src="{% static './images/logo.png' %}">
                    </a> <!-- brand-wrap.// -->
                </div>
                <div class="col-lg col-sm col-md col-6 flex-grow-0">
                    <div class="category-wrap dropdown d-inline-block float-right">
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bars"></i> All category
                        </button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">Machinery / Mechanical Parts / Tools </a>
                            <a class="dropdown-item" href="#">Consumer Electronics / Home Appliances </a>
                            <a class="dropdown-item" href="#">Auto / Transportation</a>
                            <a class="dropdown-item" href="#">Apparel / Textiles / Timepieces </a>
                            <a class="dropdown-item" href="#">Home & Garden / Construction / Lights </a>
                            <a class="dropdown-item" href="#">Beauty & Personal Care / Health </a>
                        </div>
                    </div> <!-- category-wrap.// -->
                </div> <!-- col.// -->
                <a href="{% url 'customer:store' %}" class="btn btn-outline-primary">Store</a>
                <div class="col-lg  col-md-6 col-sm-12 col">
                    <form action="#" class="search">
                        <div class="input-group w-100">
                            <input type="text" class="form-control" style="width:60%;" placeholder="Search">

                            <div class="input-group-append">
                                <button class="btn btn-primary" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form> <!-- search-wrap .end// -->
                </div> <!-- col.// -->
                <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
                    <div class="d-flex justify-content-end mb-3 mb-lg-0">
                        <div class="widget-header">
                            <small class="title text-muted">Welcome Admin!</small>
                            <div>
                                <a href="">Log Out</a> <span class="dark-transp"> | </span>

                            </div>
                        </div>

                    </div> <!-- widgets-wrap.// -->
                </div> <!-- col.// -->
            </div> <!-- row.// -->
        </div> <!-- container.// -->
    </section> <!-- header-main .// -->




</header> <!-- section-header.// -->

eKart_admin/templates/ekart_admin/includes/sidebar.html
<aside class="col-md-3">
    <!--   SIDEBAR   -->
    <ul class="list-group">
       
        
        <a class="list-group-item" href="{% url 'ekart_admin:add_category' %}"> Add category </a>
        <a class="list-group-item" href="{% url 'ekart_admin:view_category' %}"> view Category </a>
        <a class="list-group-item" href="{% url 'ekart_admin:pending_sellers' %}"> Pending sellers </a>
        <a class="list-group-item" href="{% url 'ekart_admin:approved_sellers' %}"> Approved sellers </a>
        <a class="list-group-item" href="{% url 'ekart_admin:customers' %}"> Customers </a>
    </ul>
    <br>
    <a class="btn btn-light btn-block" href="#"> <i class="fa fa-power-off"></i> <span class="text">Log
            out</span> </a>
    <!--   SIDEBAR .//END   -->
</aside>